import { useCallback, useEffect, useMemo, useState } from 'react';
import { Boxes, Check, CircuitBoard, ClipboardCheck, PackagePlus, RefreshCw, X } from 'lucide-react';

import { bimModelsApi } from '../../api/bimModels';

const emptyRegistry = { systems: [], assets: [], tests: [] };
const emptyAsset = { system_id: '', asset_tag: '', name: '', asset_type: '', manufacturer: '', model_reference: '', serial_number: '' };
const emptyTest = { asset_id: '', protocol_code: '', protocol_name: '', checklist: '', result: '', outcome: 'passed', evidence_reference: '' };

export default function BimCommissioningRegistryPanel({ projectId, empresaId, versionId, element, api = bimModelsApi }) {
    const [registry, setRegistry] = useState(emptyRegistry);
    const [mode, setMode] = useState('asset');
    const [systemForm, setSystemForm] = useState({ system_code: '', name: '', discipline: '', description: '' });
    const [assetForm, setAssetForm] = useState(emptyAsset);
    const [testForm, setTestForm] = useState(emptyTest);
    const [selectedAssetId, setSelectedAssetId] = useState(null);
    const [selectedTestId, setSelectedTestId] = useState(null);
    const [reason, setReason] = useState('');
    const [busy, setBusy] = useState(false);
    const [error, setError] = useState('');
    const load = useCallback(async () => {
        if (!projectId) return;
        try { setError(''); setRegistry({ ...emptyRegistry, ...await api.getCommissioningRegistry(projectId, empresaId) }); }
        catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo cargar el registro de commissioning.'); }
    }, [api, empresaId, projectId]);
    useEffect(() => { load(); }, [load]);
    useEffect(() => { if (element) setAssetForm((current) => ({ ...current, name: current.name || element.nombre || '', asset_type: current.asset_type || element.ifc_class || '' })); }, [element]);
    const selectedAsset = useMemo(() => registry.assets.find((item) => item.id === selectedAssetId), [registry.assets, selectedAssetId]);
    const selectedTest = useMemo(() => registry.tests.find((item) => item.id === selectedTestId), [registry.tests, selectedTestId]);
    const readySystem = useMemo(() => registry.systems.find((system) => system.status === 'commissioning' && registry.assets.some((asset) => asset.system_id === system.id) && registry.assets.filter((asset) => asset.system_id === system.id).every((asset) => asset.status === 'accepted')), [registry.assets, registry.systems]);

    const run = async (action, fallback) => { try { setBusy(true); setError(''); await action(); } catch (requestError) { setError(requestError?.response?.data?.detail || fallback); } finally { setBusy(false); } };
    const createSystem = (event) => { event.preventDefault(); run(async () => { await api.createCommissioningSystem(projectId, systemForm, empresaId); setSystemForm({ system_code: '', name: '', discipline: '', description: '' }); setMode('asset'); await load(); }, 'No se pudo registrar el sistema.'); };
    const createAsset = (event) => { event.preventDefault(); run(async () => { const value = await api.createCommissioningAsset(projectId, { ...assetForm, system_id: Number(assetForm.system_id), version_id: Number(versionId), element_id: Number(element?.id) }, empresaId); setAssetForm(emptyAsset); setSelectedAssetId(value.id); setTestForm((current) => ({ ...current, asset_id: String(value.id) })); await load(); }, 'No se pudo registrar el activo.'); };
    const createTest = (event) => { event.preventDefault(); run(async () => { const value = await api.createCommissioningTest(projectId, { ...testForm, asset_id: Number(testForm.asset_id), checklist: testForm.checklist.split('\n').map((item) => item.trim()).filter(Boolean), results: { resultado: testForm.result } }, empresaId); setTestForm({ ...emptyTest, asset_id: testForm.asset_id }); setSelectedAssetId(value.asset_id); setSelectedTestId(value.id); await load(); }, 'No se pudo presentar la prueba.'); };
    const decideTest = (decision) => run(async () => { await api.decideCommissioningTest(projectId, selectedTest.id, { decision, reason, expected_lock_version: selectedTest.lock_version }, empresaId); setReason(''); await load(); }, 'No se pudo decidir la prueba.');
    const decideAsset = (decision) => run(async () => { await api.decideCommissioningAsset(projectId, selectedAsset.id, { decision, reason, expected_lock_version: selectedAsset.lock_version }, empresaId); setReason(''); await load(); }, 'No se pudo decidir el activo.');
    const acceptSystem = (system) => run(async () => { await api.acceptCommissioningSystem(projectId, system.id, { reason, expected_lock_version: system.lock_version }, empresaId); setReason(''); await load(); }, 'No se pudo aceptar el sistema.');

    return <section className="bim-responsive-container flex h-full min-h-0 flex-col overflow-hidden border border-zinc-200 bg-white" data-bim-commissioning-registry>
        <header className="flex h-12 shrink-0 items-center justify-between border-b border-zinc-200 px-3"><div className="flex min-w-0 items-center gap-2"><CircuitBoard size={16} className="shrink-0 text-[#F39200]"/><div className="min-w-0"><h3 className="truncate text-xs font-semibold">Commissioning técnico</h3><p className="truncate text-[10px] text-zinc-500">Activos, protocolos, resultados y aceptación gobernada</p></div></div><button type="button" onClick={load} disabled={busy} aria-label="Actualizar commissioning" title="Actualizar" className="grid h-8 w-8 place-items-center border border-zinc-200"><RefreshCw size={14} className={busy?'animate-spin':''}/></button></header>
        <div className="bim-responsive-workbench flex-1" style={{ '--bim-workbench-sidebar': '360px' }}>
            <aside className="overflow-y-auto border-r border-zinc-200 p-3"><div className="grid grid-cols-3 border border-zinc-200 p-0.5" role="group" aria-label="Tipo de registro commissioning">{[['asset','Activo'],['system','Sistema'],['test','Prueba']].map(([id,label])=><button key={id} type="button" onClick={()=>setMode(id)} aria-pressed={mode===id} className={`h-8 text-xs font-semibold ${mode===id?'bg-zinc-800 text-white':'text-zinc-600'}`}>{label}</button>)}</div>
                {mode==='system'?<form onSubmit={createSystem} className="mt-3 grid gap-2"><input required aria-label="Código de sistema" placeholder="Código" value={systemForm.system_code} onChange={e=>setSystemForm({...systemForm,system_code:e.target.value})} className="h-9 border px-2 text-xs"/><input required aria-label="Nombre de sistema" placeholder="Nombre" value={systemForm.name} onChange={e=>setSystemForm({...systemForm,name:e.target.value})} className="h-9 border px-2 text-xs"/><input aria-label="Disciplina de sistema" placeholder="Disciplina" value={systemForm.discipline} onChange={e=>setSystemForm({...systemForm,discipline:e.target.value})} className="h-9 border px-2 text-xs"/><textarea aria-label="Descripción de sistema" placeholder="Descripción" value={systemForm.description} onChange={e=>setSystemForm({...systemForm,description:e.target.value})} className="h-24 resize-none border p-2 text-xs"/><button disabled={busy} className="h-9 bg-zinc-800 text-xs font-semibold text-white">Registrar sistema</button></form>:null}
                {mode==='asset'?<form onSubmit={createAsset} className="mt-3 grid gap-2"><div className="border border-orange-200 bg-orange-50 p-2 text-xs"><strong className="block truncate">{element?.nombre||'Selecciona un elemento en el visor'}</strong><code className="block truncate text-[10px] text-zinc-600">{element?.global_id||'Sin GUID seleccionado'}</code></div><select required aria-label="Sistema del activo" value={assetForm.system_id} onChange={e=>setAssetForm({...assetForm,system_id:e.target.value})} className="h-9 border px-2 text-xs"><option value="">Sistema</option>{registry.systems.filter(x=>['registered','commissioning'].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.system_code} · {x.name}</option>)}</select><input required aria-label="Tag del activo" placeholder="Tag único" value={assetForm.asset_tag} onChange={e=>setAssetForm({...assetForm,asset_tag:e.target.value})} className="h-9 border px-2 text-xs"/><input required aria-label="Nombre del activo" placeholder="Nombre" value={assetForm.name} onChange={e=>setAssetForm({...assetForm,name:e.target.value})} className="h-9 border px-2 text-xs"/><input required aria-label="Tipo de activo" placeholder="Tipo" value={assetForm.asset_type} onChange={e=>setAssetForm({...assetForm,asset_type:e.target.value})} className="h-9 border px-2 text-xs"/><div className="grid grid-cols-2 gap-2"><input aria-label="Fabricante del activo" placeholder="Fabricante" value={assetForm.manufacturer} onChange={e=>setAssetForm({...assetForm,manufacturer:e.target.value})} className="h-9 min-w-0 border px-2 text-xs"/><input aria-label="Modelo del activo" placeholder="Modelo" value={assetForm.model_reference} onChange={e=>setAssetForm({...assetForm,model_reference:e.target.value})} className="h-9 min-w-0 border px-2 text-xs"/></div><input aria-label="Serie del activo" placeholder="Número de serie" value={assetForm.serial_number} onChange={e=>setAssetForm({...assetForm,serial_number:e.target.value})} className="h-9 border px-2 text-xs"/><button disabled={busy||!element||!versionId||!registry.systems.length} className="flex h-9 items-center justify-center gap-1 bg-zinc-800 text-xs font-semibold text-white disabled:opacity-40"><PackagePlus size={13}/>Registrar activo</button></form>:null}
                {mode==='test'?<form onSubmit={createTest} className="mt-3 grid gap-2"><select required aria-label="Activo de la prueba" value={testForm.asset_id} onChange={e=>{setTestForm({...testForm,asset_id:e.target.value});setSelectedAssetId(Number(e.target.value));}} className="h-9 border px-2 text-xs"><option value="">Activo</option>{registry.assets.filter(x=>!['accepted','retired'].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.asset_tag} · {x.name}</option>)}</select><input required aria-label="Código de protocolo" placeholder="Código de protocolo" value={testForm.protocol_code} onChange={e=>setTestForm({...testForm,protocol_code:e.target.value})} className="h-9 border px-2 text-xs"/><input required aria-label="Nombre de protocolo" placeholder="Nombre de protocolo" value={testForm.protocol_name} onChange={e=>setTestForm({...testForm,protocol_name:e.target.value})} className="h-9 border px-2 text-xs"/><textarea required aria-label="Lista de comprobación" placeholder="Una comprobación por línea" value={testForm.checklist} onChange={e=>setTestForm({...testForm,checklist:e.target.value})} className="h-24 resize-none border p-2 text-xs"/><textarea required aria-label="Resultado de prueba" placeholder="Resultado medido" value={testForm.result} onChange={e=>setTestForm({...testForm,result:e.target.value})} className="h-20 resize-none border p-2 text-xs"/><div className="grid grid-cols-2 gap-2"><select aria-label="Resultado técnico" value={testForm.outcome} onChange={e=>setTestForm({...testForm,outcome:e.target.value})} className="h-9 border px-2 text-xs"><option value="passed">Superada</option><option value="failed">Fallida</option></select><input aria-label="Referencia de evidencia" placeholder="Evidencia" value={testForm.evidence_reference} onChange={e=>setTestForm({...testForm,evidence_reference:e.target.value})} className="h-9 min-w-0 border px-2 text-xs"/></div><button disabled={busy||!testForm.asset_id} className="flex h-9 items-center justify-center gap-1 bg-zinc-800 text-xs font-semibold text-white disabled:opacity-40"><ClipboardCheck size={13}/>Presentar prueba</button></form>:null}
                {error?<p role="alert" className="mt-2 text-xs text-red-700">{error}</p>:null}</aside>
            <main className="flex min-w-0 flex-col overflow-hidden" data-bim-commissioning-ledger><div className="grid shrink-0 grid-cols-4 border-b border-zinc-200 bg-zinc-50 px-4 py-3 text-xs">{[[registry.systems.length,'sistemas'],[registry.assets.length,'activos'],[registry.tests.length,'pruebas'],[registry.assets.filter(x=>x.status==='accepted').length,'aceptados']].map(([value,label])=><span key={label}><strong className="block text-lg">{value}</strong>{label}</span>)}</div><div className="min-h-0 flex-1 overflow-y-auto">{registry.systems.map(system=><section key={system.id} className="border-b border-zinc-200"><header className="flex items-center gap-2 bg-white px-4 py-2"><Boxes size={14} className="text-[#F39200]"/><strong className="text-xs">{system.system_code} · {system.name}</strong><span className="ml-auto text-[10px] uppercase text-zinc-500">{system.asset_count} activos · {system.status}</span></header>{registry.assets.filter(asset=>asset.system_id===system.id).map(asset=><div key={asset.id}><button type="button" onClick={()=>{setSelectedAssetId(asset.id);setTestForm(current=>({...current,asset_id:String(asset.id)}));}} className={`grid w-full grid-cols-[110px_minmax(180px,1fr)_110px_90px] gap-3 border-t px-4 py-2 text-left text-xs ${selectedAssetId===asset.id?'bg-orange-50':'hover:bg-zinc-50'}`}><strong>{asset.asset_tag}</strong><span className="truncate">{asset.name}<small className="block truncate text-zinc-500">{asset.asset_type} · {asset.global_id}</small></span><span>{registry.tests.filter(test=>test.asset_id===asset.id).length} pruebas</span><span className="uppercase text-zinc-500">{asset.status}</span></button>{registry.tests.filter(test=>test.asset_id===asset.id).map(test=><button type="button" key={test.id} onClick={()=>{setSelectedAssetId(asset.id);setSelectedTestId(test.id);}} className={`grid w-full grid-cols-[110px_minmax(180px,1fr)_110px_90px] gap-3 border-t border-zinc-100 py-2 pl-10 pr-4 text-left text-[11px] ${selectedTestId===test.id?'bg-amber-50':'text-zinc-600 hover:bg-zinc-50'}`}><code>{test.protocol_code} · #{test.attempt}</code><span className="truncate">{test.protocol_name}</span><span>{test.outcome}</span><span className="uppercase">{test.status}</span></button>)}</div>)}</section>)}{!registry.systems.length?<p className="p-8 text-center text-xs text-zinc-500">Registra el primer sistema de commissioning.</p>:null}</div>
                {(selectedTest?.status==='submitted'||selectedAsset&&['testing','rejected'].includes(selectedAsset.status)||readySystem)?<footer className="grid shrink-0 grid-cols-[minmax(0,1fr)_100px_100px] gap-2 border-t border-zinc-200 p-3"><input aria-label="Motivo de decisión commissioning" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo verificable" className="h-9 min-w-0 border px-2 text-xs"/>{selectedTest?.status==='submitted'?<><button type="button" onClick={()=>decideTest('accepted')} disabled={busy||reason.length<5||selectedTest.outcome!=='passed'} className="flex items-center justify-center gap-1 bg-emerald-700 text-xs font-semibold text-white disabled:opacity-40"><Check size={13}/>Aprobar</button><button type="button" onClick={()=>decideTest('rejected')} disabled={busy||reason.length<5} className="flex items-center justify-center gap-1 border text-xs font-semibold text-red-700 disabled:opacity-40"><X size={13}/>Rechazar</button></>:selectedAsset&&['testing','rejected'].includes(selectedAsset.status)?<><button type="button" onClick={()=>decideAsset('accepted')} disabled={busy||reason.length<5} className="flex items-center justify-center gap-1 bg-emerald-700 text-xs font-semibold text-white disabled:opacity-40"><Check size={13}/>Aceptar</button><button type="button" onClick={()=>decideAsset('rejected')} disabled={busy||reason.length<5} className="flex items-center justify-center gap-1 border text-xs font-semibold text-red-700 disabled:opacity-40"><X size={13}/>Rechazar</button></>:<><button type="button" onClick={()=>acceptSystem(readySystem)} disabled={busy||reason.length<5} className="col-span-2 flex items-center justify-center gap-1 bg-emerald-700 text-xs font-semibold text-white disabled:opacity-40"><Check size={13}/>Aceptar sistema</button></>}</footer>:null}
            </main>
        </div>
    </section>;
}
