import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Archive, Check, FileCheck2, RefreshCw, X } from 'lucide-react';

import { bimModelsApi } from '../../api/bimModels';

export default function BimHandoverDossierPanel({ projectId, empresaId, api = bimModelsApi }) {
    const [items, setItems] = useState([]);
    const [form, setForm] = useState({ revision: '', assembly_notes: '' });
    const [selectedId, setSelectedId] = useState(null);
    const [reason, setReason] = useState('');
    const [busy, setBusy] = useState(false);
    const [error, setError] = useState('');
    const [createOpen, setCreateOpen] = useState(false);
    const createTriggerRef = useRef(null);
    const createDialogRef = useRef(null);
    const selected = useMemo(() => items.find((item) => item.id === selectedId), [items, selectedId]);
    const load = useCallback(async () => { if (!projectId) return; try { setError(''); setItems(await api.listHandoverDossiers(projectId, empresaId)); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudieron cargar los dossiers de entrega.'); } }, [api, empresaId, projectId]);
    useEffect(() => { load(); }, [load]);
    const openCreate = () => setCreateOpen(true);
    const closeCreate = useCallback(() => { setCreateOpen(false); requestAnimationFrame(() => createTriggerRef.current?.focus()); }, []);
    useEffect(() => {
        if (!createOpen) return undefined;
        const handleKeyDown = (event) => {
            if (event.key === 'Escape') { event.preventDefault(); closeCreate(); return; }
            if (event.key !== 'Tab') return;
            const focusable = [...(createDialogRef.current?.querySelectorAll('button:not([disabled]), input:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])') || [])];
            if (!focusable.length) return;
            const first = focusable[0]; const last = focusable[focusable.length - 1];
            if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
            else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
        };
        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [closeCreate, createOpen]);
    const create = async (event) => { event.preventDefault(); try { setBusy(true); setError(''); const value = await api.createHandoverDossier(projectId, form, empresaId); setItems((current) => [value, ...current]); setSelectedId(value.id); setForm({ revision: '', assembly_notes: '' }); closeCreate(); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo ensamblar el dossier digital.'); } finally { setBusy(false); } };
    const decide = async (decision) => { try { setBusy(true); setError(''); const value = await api.decideHandoverDossier(projectId, selected.id, { decision, reason, expected_lock_version: selected.lock_version }, empresaId); setItems((current) => current.map((item) => item.id === value.id ? value : item)); setReason(''); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo decidir el dossier digital.'); } finally { setBusy(false); } };
    return <section className="relative flex h-full min-h-0 flex-col overflow-hidden border border-zinc-200 bg-white" data-bim-handover-dossier>
        <header className="flex min-h-12 shrink-0 items-center justify-between border-b border-zinc-200 px-4"><div className="flex min-w-0 items-center gap-2"><Archive size={16} className="text-orange-600"/><div className="min-w-0"><h3 className="truncate text-xs font-semibold text-zinc-950">Dossier digital de entrega</h3><p className="truncate text-[10px] text-zinc-600">As-built · punch · commissioning · documentos CDE</p></div></div><button type="button" onClick={load} disabled={busy} aria-label="Actualizar dossiers digitales" className="inline-flex size-8 items-center justify-center rounded-md border border-zinc-300 text-zinc-600"><RefreshCw size={14} className={busy ? 'animate-spin' : ''}/></button></header>
        <div className="flex min-h-14 shrink-0 items-center gap-5 border-b border-zinc-200 bg-zinc-50 px-4"><div><span className="block text-[9px] text-zinc-500">Dossiers</span><strong className="text-xs">{items.length}</strong></div><div className="h-7 w-px bg-zinc-200"/><div><span className="block text-[9px] text-zinc-500">En revisión</span><strong className="text-xs">{items.filter((item) => item.status === 'submitted').length}</strong></div><div><span className="block text-[9px] text-zinc-500">Aceptados</span><strong className="text-xs">{items.filter((item) => item.status === 'accepted').length}</strong></div><button ref={createTriggerRef} type="button" onClick={openCreate} className="ml-auto inline-flex h-9 items-center gap-2 rounded-md bg-orange-600 px-3 text-xs font-semibold text-white active:scale-[.97]"><FileCheck2 size={13}/>Nuevo dossier</button></div>
        {error ? <p role="alert" className="shrink-0 border-b border-rose-200 bg-rose-50 px-4 py-2 text-xs text-rose-800">{error}</p> : null}
        <main className="flex min-w-0 min-h-0 flex-1 flex-col overflow-hidden"><div className="min-h-0 flex-1 overflow-y-auto" data-bim-handover-dossier-ledger><table className="w-full min-w-[60rem] border-collapse text-left text-xs"><thead className="sticky top-0 z-10 bg-white text-[10px] font-semibold text-zinc-600"><tr className="border-b border-zinc-200"><th className="w-32 px-4 py-2.5">Revisión</th><th className="w-28 px-3 py-2.5">Estado</th><th className="w-24 px-3 py-2.5">Sistemas</th><th className="w-24 px-3 py-2.5">Activos</th><th className="w-28 px-3 py-2.5">Documentos</th><th className="px-3 py-2.5">Manifiesto y dependencias</th></tr></thead><tbody className="divide-y divide-zinc-200">{items.map((item) => <tr key={item.id} onClick={() => setSelectedId(item.id)} className={`cursor-pointer ${selected?.id === item.id ? 'bg-orange-50' : 'hover:bg-zinc-50'}`}><td className="px-4 py-3 font-semibold">{item.revision}</td><td className="px-3 py-3"><span className="rounded bg-zinc-100 px-2 py-1 text-[10px] font-semibold">{item.status}</span></td><td className="px-3 py-3 font-semibold">{item.total_systems}</td><td className="px-3 py-3 font-semibold">{item.total_assets}</td><td className="px-3 py-3 font-semibold">{item.total_documents}</td><td className="min-w-0 px-3 py-3"><code className="block truncate text-[10px]">{item.manifest_checksum_sha256}</code><span className="mt-1 block truncate text-[10px] text-zinc-500">As-built #{item.as_built_acceptance_id} · Punch #{item.punch_closure_id}</span></td></tr>)}</tbody></table>{!items.length ? <p className="p-8 text-center text-xs text-zinc-500">Sin dossiers digitales ensamblados.</p> : null}</div>{selected?.status === 'submitted' ? <footer className="grid shrink-0 grid-cols-[minmax(0,1fr)_7rem_7rem] gap-2 border-t border-zinc-200 p-3"><input aria-label="Motivo de decisión del dossier" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Motivo verificable" className="h-9 min-w-0 rounded-md border border-zinc-300 px-3 text-xs"/><button type="button" onClick={() => decide('accepted')} disabled={busy || reason.length < 5} className="inline-flex h-9 items-center justify-center gap-1 rounded-md bg-emerald-700 text-xs font-semibold text-white disabled:opacity-40"><Check size={13}/>Aceptar</button><button type="button" onClick={() => decide('rejected')} disabled={busy || reason.length < 5} className="inline-flex h-9 items-center justify-center gap-1 rounded-md border border-rose-200 text-xs font-semibold text-rose-700 disabled:opacity-40"><X size={13}/>Rechazar</button></footer> : null}</main>
        {createOpen && typeof document !== 'undefined' ? createPortal(<div className="fixed inset-0 z-[1300] grid place-items-center bg-zinc-950/35 p-6"><form ref={createDialogRef} onSubmit={create} className="w-full max-w-xl overflow-hidden rounded-xl bg-white shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="handover-create-title"><header className="flex min-h-14 items-center border-b border-zinc-200 px-5"><div><h3 id="handover-create-title" className="text-sm font-semibold">Nuevo dossier digital</h3><p className="text-[11px] text-zinc-600">Ensambla las evidencias actuales del proyecto.</p></div><button type="button" onClick={closeCreate} aria-label="Cerrar nuevo dossier" className="ml-auto inline-flex size-8 items-center justify-center rounded-md text-zinc-500 hover:bg-zinc-100"><X size={16}/></button></header><div className="space-y-4 p-5"><label className="block text-[11px] font-semibold">Revisión<input autoFocus required aria-label="Revisión del dossier digital" placeholder="ENT-01" value={form.revision} onChange={(event) => setForm({ ...form, revision: event.target.value })} className="mt-1 h-9 w-full rounded-md border border-zinc-300 px-3 text-xs font-normal"/></label><label className="block text-[11px] font-semibold">Notas de ensamblado<textarea required minLength={5} aria-label="Notas de ensamblado del dossier" placeholder="Alcance, comprobaciones y excepciones" value={form.assembly_notes} onChange={(event) => setForm({ ...form, assembly_notes: event.target.value })} className="mt-1 h-32 w-full resize-none rounded-md border border-zinc-300 p-3 text-xs font-normal"/></label></div><footer className="flex min-h-14 items-center justify-end gap-2 border-t border-zinc-200 px-5"><button type="button" onClick={closeCreate} className="h-9 px-3 text-xs font-semibold text-zinc-600">Cancelar</button><button type="submit" disabled={busy} className="h-9 rounded-md bg-orange-600 px-4 text-xs font-semibold text-white disabled:opacity-40">{busy ? 'Ensamblando…' : 'Ensamblar dossier'}</button></footer></form></div>, document.body) : null}
    </section>;
}
