import { useCallback, useEffect, useState } from 'react';
import { Archive, FileCheck2, RefreshCw } from 'lucide-react';

import { bimModelsApi } from '../../api/bimModels';

export default function BimHandoverDossierPanel({ projectId, empresaId, api = bimModelsApi }) {
    const [items, setItems] = useState([]);
    const [form, setForm] = useState({ revision: '', assembly_notes: '' });
    const [busy, setBusy] = useState(false);
    const [error, setError] = useState('');
    const load = useCallback(async () => { if (!projectId) return; try { setError(''); setItems(await api.listHandoverDossiers(projectId, empresaId)); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudieron cargar los dossiers de entrega.'); } }, [api, empresaId, projectId]);
    useEffect(() => { load(); }, [load]);
    const create = async (event) => { event.preventDefault(); try { setBusy(true); setError(''); const value = await api.createHandoverDossier(projectId, form, empresaId); setItems((current) => [value, ...current]); setForm({ revision: '', assembly_notes: '' }); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo ensamblar el dossier digital.'); } finally { setBusy(false); } };
    return <section className="flex h-full min-h-0 flex-col overflow-hidden border border-zinc-200 bg-white" data-bim-handover-dossier>
        <header className="flex h-12 shrink-0 items-center justify-between border-b border-zinc-200 px-3"><div className="flex min-w-0 items-center gap-2"><Archive size={16} className="text-[#F39200]"/><div className="min-w-0"><h3 className="truncate text-xs font-semibold">Dossier digital de entrega</h3><p className="truncate text-[10px] text-zinc-500">As-built · punch · commissioning · documentos CDE</p></div></div><button type="button" onClick={load} disabled={busy} aria-label="Actualizar dossiers digitales" title="Actualizar" className="grid h-8 w-8 place-items-center border border-zinc-200"><RefreshCw size={14} className={busy ? 'animate-spin' : ''}/></button></header>
        <div className="grid min-h-0 flex-1 grid-cols-[360px_minmax(0,1fr)]"><aside className="overflow-y-auto border-r border-zinc-200 p-3"><form onSubmit={create} className="grid gap-2"><input required aria-label="Revisión del dossier digital" placeholder="Revisión" value={form.revision} onChange={(event) => setForm({ ...form, revision: event.target.value })} className="h-9 border px-2 text-xs"/><textarea required minLength={5} aria-label="Notas de ensamblado del dossier" placeholder="Alcance, comprobaciones y excepciones" value={form.assembly_notes} onChange={(event) => setForm({ ...form, assembly_notes: event.target.value })} className="h-40 resize-none border p-2 text-xs"/><button disabled={busy} className="flex h-9 items-center justify-center gap-1 bg-zinc-800 text-xs font-semibold text-white disabled:opacity-40"><FileCheck2 size={13}/>Ensamblar dossier</button></form>{error ? <p role="alert" className="mt-2 text-xs text-red-700">{error}</p> : null}</aside>
            <main className="min-w-0 overflow-y-auto" data-bim-handover-dossier-ledger>{items.map((item) => <article key={item.id} className="grid grid-cols-[120px_100px_100px_100px_minmax(220px,1fr)] gap-3 border-b px-4 py-3 text-xs"><span><strong className="block">{item.revision}</strong><small className="uppercase text-zinc-500">{item.status}</small></span><span><strong className="block text-lg">{item.total_systems}</strong>sistemas</span><span><strong className="block text-lg">{item.total_assets}</strong>activos</span><span><strong className="block text-lg">{item.total_documents}</strong>documentos</span><span className="min-w-0"><small className="block text-zinc-500">Huella del manifiesto</small><code className="block truncate text-[10px]">{item.manifest_checksum_sha256}</code><small className="mt-1 block truncate text-zinc-500">As-built #{item.as_built_acceptance_id} · Punch #{item.punch_closure_id}</small></span></article>)}{!items.length ? <p className="p-8 text-center text-xs text-zinc-500">Sin dossiers digitales ensamblados.</p> : null}</main></div>
    </section>;
}
