import { useCallback, useEffect, useMemo, useState } from 'react';
import { Check, ClipboardCheck, RefreshCw, ShieldCheck, X } from 'lucide-react';

import { bimModelsApi } from '../../api/bimModels';

export default function BimPunchClosurePanel({ projectId, empresaId, api = bimModelsApi }) {
    const [items, setItems] = useState([]);
    const [form, setForm] = useState({ revision: '', criteria: 'Sin hallazgos abiertos\nEvidencias verificadas', verification_notes: '' });
    const [selectedId, setSelectedId] = useState(null);
    const [reason, setReason] = useState('');
    const [busy, setBusy] = useState(false);
    const [error, setError] = useState('');
    const selected = useMemo(() => items.find((item) => item.id === selectedId), [items, selectedId]);
    const load = useCallback(async () => { if (!projectId) return; try { setError(''); setItems(await api.listPunchClosures(projectId, empresaId)); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudieron cargar los cierres punch.'); } }, [api, empresaId, projectId]);
    useEffect(() => { load(); }, [load]);
    const create = async (event) => { event.preventDefault(); try { setBusy(true); setError(''); const value = await api.createPunchClosure(projectId, { revision: form.revision, closure_criteria: form.criteria.split('\n').map((item) => item.trim()).filter(Boolean), verification_notes: form.verification_notes }, empresaId); setItems((current) => [value, ...current]); setSelectedId(value.id); setForm({ revision: '', criteria: form.criteria, verification_notes: '' }); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo presentar el cierre punch.'); } finally { setBusy(false); } };
    const decide = async (decision) => { try { setBusy(true); setError(''); const value = await api.decidePunchClosure(projectId, selected.id, { decision, reason, expected_lock_version: selected.lock_version }, empresaId); setItems((current) => current.map((item) => item.id === value.id ? value : item)); setReason(''); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo decidir el cierre punch.'); } finally { setBusy(false); } };
    return <section className="flex h-full min-h-0 flex-col overflow-hidden border border-zinc-200 bg-white" data-bim-punch-closure>
        <header className="flex h-12 shrink-0 items-center justify-between border-b border-zinc-200 px-3"><div className="flex min-w-0 items-center gap-2"><ShieldCheck size={16} className="text-[#F39200]"/><div className="min-w-0"><h3 className="truncate text-xs font-semibold">Cierre de punch list</h3><p className="truncate text-[10px] text-zinc-500">As-built vigente · inventario congelado · decisión auditable</p></div></div><button type="button" onClick={load} disabled={busy} aria-label="Actualizar cierres punch" title="Actualizar" className="grid h-8 w-8 place-items-center border border-zinc-200"><RefreshCw size={14} className={busy?'animate-spin':''}/></button></header>
        <div className="grid min-h-0 flex-1 grid-cols-[360px_minmax(0,1fr)]"><aside className="overflow-y-auto border-r border-zinc-200 p-3"><form onSubmit={create} className="grid gap-2"><input required aria-label="Revisión de cierre punch" placeholder="Revisión" value={form.revision} onChange={e=>setForm({...form,revision:e.target.value})} className="h-9 border px-2 text-xs"/><textarea required aria-label="Criterios de cierre punch" value={form.criteria} onChange={e=>setForm({...form,criteria:e.target.value})} className="h-24 resize-none border p-2 text-xs"/><textarea required minLength={5} aria-label="Verificación de cierre punch" placeholder="Recorrido, evidencias y excepciones" value={form.verification_notes} onChange={e=>setForm({...form,verification_notes:e.target.value})} className="h-32 resize-none border p-2 text-xs"/><button disabled={busy} className="flex h-9 items-center justify-center gap-1 bg-zinc-800 text-xs font-semibold text-white disabled:opacity-40"><ClipboardCheck size={13}/>Presentar cierre</button></form>{error?<p role="alert" className="mt-2 text-xs text-red-700">{error}</p>:null}</aside>
            <main className="flex min-w-0 flex-col overflow-hidden"><div className="min-h-0 flex-1 overflow-y-auto" data-bim-punch-closure-ledger>{items.map(item=><button type="button" key={item.id} onClick={()=>setSelectedId(item.id)} className={`grid w-full grid-cols-[110px_100px_100px_minmax(180px,1fr)_110px] gap-3 border-b px-4 py-3 text-left text-xs ${selectedId===item.id?'bg-orange-50':'hover:bg-zinc-50'}`}><span><strong className="block">{item.revision}</strong><small className="uppercase text-zinc-500">{item.status}</small></span><span><strong className="block text-lg">{item.total_items}</strong>hallazgos</span><span><strong className="block text-lg text-red-700">{item.critical_items}</strong>críticos</span><span className="min-w-0"><small className="block text-zinc-500">Huella punch</small><code className="block truncate text-[10px]">{item.punch_snapshot_sha256}</code></span><span><small className="block text-zinc-500">As-built</small><strong>#{item.as_built_acceptance_id}</strong></span></button>)}{!items.length?<p className="p-8 text-center text-xs text-zinc-500">Sin cierres punch presentados.</p>:null}</div>{selected?.status==='submitted'?<footer className="grid shrink-0 grid-cols-[minmax(0,1fr)_100px_100px] gap-2 border-t p-3"><input aria-label="Motivo de decisión de cierre punch" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo verificable" className="h-9 min-w-0 border px-2 text-xs"/><button type="button" onClick={()=>decide('accepted')} disabled={busy||reason.length<5} className="flex items-center justify-center gap-1 bg-emerald-700 text-xs font-semibold text-white disabled:opacity-40"><Check size={13}/>Aceptar</button><button type="button" onClick={()=>decide('rejected')} disabled={busy||reason.length<5} className="flex items-center justify-center gap-1 border text-xs font-semibold text-red-700 disabled:opacity-40"><X size={13}/>Rechazar</button></footer>:null}</main></div>
    </section>;
}
