import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Plus, RefreshCw, XCircle } from 'lucide-react';

import { bimModelsApi } from '../../api/bimModels';

const TYPES = { weather: 'Clima', design_change: 'Cambio de diseño', supply: 'Suministro', safety: 'Seguridad', quality: 'Calidad', other: 'Otro' };
const STATUS = { reported: 'Reportado', validated: 'Validado', void: 'Anulado' };
const emptyForm = { activity_snapshot_id: '', work_area_id: '', event_type: 'weather', title: '', description: '', occurred_at: '', delay_days: '0', actual_cost: '0' };

export default function BimUnplannedEventsPanel({ projectId, empresaId, api = bimModelsApi }) {
    const [events, setEvents] = useState([]); const [activities, setActivities] = useState([]); const [areas, setAreas] = useState([]);
    const [selectedId, setSelectedId] = useState(null); const [form, setForm] = useState(emptyForm); const [reason, setReason] = useState('');
    const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
    const load = useCallback(async () => { if (!projectId) return; try { setMessage(''); const [eventRows, activityRows, areaRows] = await Promise.all([api.list4dUnplannedEvents(projectId, empresaId), api.list4dActivities(projectId, empresaId), api.list4dWorkAreas(projectId, empresaId)]); setEvents(eventRows || []); setActivities(activityRows || []); setAreas(areaRows || []); setSelectedId((current) => eventRows.some((item) => item.id === current) ? current : eventRows[0]?.id || null); setForm((current) => ({ ...current, activity_snapshot_id: current.activity_snapshot_id || String(activityRows[0]?.id || '') })); } catch (error) { setMessage(error?.response?.data?.detail || 'No se pudieron cargar los eventos BIM.'); } }, [api, empresaId, projectId]);
    useEffect(() => { load(); }, [load]);
    const selected = events.find((item) => item.id === selectedId) || null;
    const validated = useMemo(() => events.filter((item) => item.status === 'validated'), [events]);
    const totals = useMemo(() => ({ delay: validated.reduce((sum, item) => sum + Number(item.delay_days || 0), 0), cost: validated.reduce((sum, item) => sum + Number(item.actual_cost || 0), 0) }), [validated]);
    const activity = (id) => activities.find((item) => item.id === id);
    const create = async () => { if (!form.activity_snapshot_id || form.title.trim().length < 3 || form.description.trim().length < 3 || !form.occurred_at) return; try { setBusy(true); const item = await api.create4dUnplannedEvent(projectId, { ...form, activity_snapshot_id: Number(form.activity_snapshot_id), work_area_id: form.work_area_id ? Number(form.work_area_id) : null, occurred_at: new Date(form.occurred_at).toISOString(), delay_days: Number(form.delay_days), actual_cost: Number(form.actual_cost) }, empresaId); setForm({ ...emptyForm, activity_snapshot_id: form.activity_snapshot_id }); await load(); setSelectedId(item.id); } catch (error) { setMessage(error?.response?.data?.detail || 'No se pudo registrar el evento.'); } finally { setBusy(false); } };
    const decide = async (action) => { if (!selected || reason.trim().length < 3) return; try { setBusy(true); const item = await api.decide4dUnplannedEvent(projectId, selected.id, { action, reason: reason.trim() }, empresaId); setEvents((current) => current.map((entry) => entry.id === item.id ? item : entry)); setReason(''); } catch (error) { setMessage(error?.response?.data?.detail || 'No se pudo decidir el evento.'); } finally { setBusy(false); } };
    return <section className="bim-responsive-container relative flex h-full min-h-0 flex-col overflow-hidden rounded-lg border border-zinc-200 bg-white" data-bim-unplanned-events>
        <header className="flex h-11 shrink-0 items-center justify-between border-b border-zinc-200 px-3"><div className="flex items-center gap-2"><AlertTriangle size={16} className="text-[#F39200]" /><div><h3 className="text-xs font-semibold text-zinc-900">Eventos no planificados</h3><p className="text-[10px] text-zinc-500">{events.length} eventos · {validated.length} validados</p></div></div><div className="flex items-center gap-5 text-[10px]"><span><strong className="text-sm text-zinc-900">{totals.delay.toFixed(1)}</strong> días</span><span><strong className="text-sm text-zinc-900">${totals.cost.toLocaleString('en-US')}</strong> coste real</span><button type="button" onClick={load} className="grid h-8 w-8 place-items-center rounded-md border border-zinc-200 text-zinc-500" title="Actualizar"><RefreshCw size={14} /></button></div></header>
        <div className="bim-responsive-three-column bim-responsive-events min-h-0 flex-1 divide-x divide-zinc-200">
            <aside className="min-h-0 overflow-y-auto" data-bim-unplanned-event-list>{events.map((item) => <button key={item.id} type="button" onClick={() => setSelectedId(item.id)} className={`w-full border-b border-zinc-100 px-3 py-3 text-left ${item.id === selectedId ? 'bg-orange-50' : 'hover:bg-zinc-50'}`}><div className="flex justify-between gap-2"><span className="truncate text-xs font-semibold text-zinc-900">{item.title}</span><span className={`text-[9px] font-semibold uppercase ${item.status === 'validated' ? 'text-emerald-700' : item.status === 'void' ? 'text-zinc-400' : 'text-amber-700'}`}>{STATUS[item.status]}</span></div><p className="mt-1 text-[10px] text-zinc-500">{TYPES[item.event_type]} · {activity(item.activity_snapshot_id)?.activity_code || item.activity_snapshot_id}</p><div className="mt-2 flex gap-4 text-[10px]"><span>{Number(item.delay_days).toFixed(1)} días</span><span>${Number(item.actual_cost).toLocaleString('en-US')}</span></div></button>)}</aside>
            <div className="min-h-0 overflow-y-auto p-3"><h4 className="mb-3 text-xs font-semibold text-zinc-900">Registrar evento</h4><div className="grid grid-cols-2 gap-2"><select aria-label="Actividad del evento" value={form.activity_snapshot_id} onChange={(event) => setForm({ ...form, activity_snapshot_id: event.target.value })} className="h-8 rounded-md border border-zinc-200 px-2 text-xs"><option value="">Actividad</option>{activities.map((item) => <option key={item.id} value={item.id}>{item.activity_code} · {item.activity_name}</option>)}</select><select aria-label="Frente del evento" value={form.work_area_id} onChange={(event) => setForm({ ...form, work_area_id: event.target.value })} className="h-8 rounded-md border border-zinc-200 px-2 text-xs"><option value="">Sin frente</option>{areas.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><select aria-label="Tipo de evento" value={form.event_type} onChange={(event) => setForm({ ...form, event_type: event.target.value })} className="h-8 rounded-md border border-zinc-200 px-2 text-xs">{Object.entries(TYPES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input aria-label="Fecha del evento" type="datetime-local" value={form.occurred_at} onChange={(event) => setForm({ ...form, occurred_at: event.target.value })} className="h-8 rounded-md border border-zinc-200 px-2 text-xs" /><input aria-label="Título del evento" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Título" className="col-span-2 h-8 rounded-md border border-zinc-200 px-2 text-xs" /><textarea aria-label="Descripción del evento" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Descripción" className="col-span-2 h-20 resize-none rounded-md border border-zinc-200 p-2 text-xs" /><label className="text-[10px] text-zinc-500">Impacto, días<input aria-label="Días de impacto" type="number" min="0" step="0.1" value={form.delay_days} onChange={(event) => setForm({ ...form, delay_days: event.target.value })} className="mt-1 h-8 w-full rounded-md border border-zinc-200 px-2 text-xs" /></label><label className="text-[10px] text-zinc-500">Coste real<input aria-label="Coste real del evento" type="number" min="0" step="0.01" value={form.actual_cost} onChange={(event) => setForm({ ...form, actual_cost: event.target.value })} className="mt-1 h-8 w-full rounded-md border border-zinc-200 px-2 text-xs" /></label></div><button type="button" onClick={create} disabled={busy || !form.activity_snapshot_id || !form.occurred_at || form.title.trim().length < 3 || form.description.trim().length < 3} className="mt-3 flex h-8 w-full items-center justify-center gap-1 rounded-md bg-zinc-900 text-xs font-semibold text-white disabled:opacity-40"><Plus size={14} />Registrar</button></div>
            <div className="min-h-0 overflow-y-auto p-4" data-bim-unplanned-event-detail>{selected ? <div><div className="flex items-start justify-between border-b border-zinc-200 pb-3"><div><p className="text-[10px] font-semibold uppercase text-[#F39200]">{TYPES[selected.event_type]}</p><h4 className="mt-1 text-base font-semibold text-zinc-900">{selected.title}</h4><p className="mt-1 text-xs text-zinc-500">{activity(selected.activity_snapshot_id)?.activity_code} · {new Date(selected.occurred_at).toLocaleString('es')}</p></div><span className="rounded bg-zinc-100 px-2 py-1 text-[10px] font-semibold">{STATUS[selected.status]}</span></div><div className="grid grid-cols-2 gap-3 border-b border-zinc-200 py-4"><div><p className="text-[10px] text-zinc-500">Impacto temporal</p><strong className="text-xl text-zinc-900">{Number(selected.delay_days).toFixed(1)} días</strong></div><div><p className="text-[10px] text-zinc-500">Coste real</p><strong className="text-xl text-zinc-900">${Number(selected.actual_cost).toLocaleString('en-US')}</strong></div></div><div className="py-4"><h5 className="text-xs font-semibold text-zinc-900">Descripción</h5><p className="mt-2 text-xs leading-5 text-zinc-600">{selected.description}</p></div>{selected.status === 'reported' ? <div className="border-t border-zinc-200 pt-3"><input aria-label="Motivo de decisión del evento" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Motivo de decisión" className="h-8 w-full rounded-md border border-zinc-200 px-2 text-xs" /><div className="mt-2 flex gap-2"><button type="button" disabled={busy || reason.trim().length < 3} onClick={() => decide('validate')} className="flex h-8 flex-1 items-center justify-center gap-1 rounded-md bg-emerald-700 text-xs text-white disabled:opacity-40"><CheckCircle2 size={14} />Validar</button><button type="button" disabled={busy || reason.trim().length < 3} onClick={() => decide('void')} className="flex h-8 flex-1 items-center justify-center gap-1 rounded-md border border-zinc-200 text-xs disabled:opacity-40"><XCircle size={14} />Anular</button></div></div> : <div className="border-t border-zinc-200 pt-3"><p className="text-[10px] text-zinc-500">Decisión</p><p className="mt-1 text-xs text-zinc-700">{selected.decision_reason}</p></div>}</div> : <p className="text-xs text-zinc-500">Sin eventos registrados.</p>}</div>
        </div>{message ? <p role="alert" className="absolute bottom-3 right-3 rounded bg-rose-50 px-2 py-1 text-[10px] text-rose-700">{message}</p> : null}
    </section>;
}
