export const INDIRECTOS_CATEGORIAS = [
  { id: 1, codigo: "1.1", descripcion: "Beneficios" },
  { id: 2, codigo: "1.2", descripcion: "Personal Tecnico" },
  { id: 3, codigo: "1.3", descripcion: "Materiales de Ingenieria" },
  { id: 4, codigo: "1.4", descripcion: "Oficina de la Obra" },
  { id: 5, codigo: "2.1", descripcion: "Personal de Servicio" },
  { id: 6, codigo: "2.2", descripcion: "Transporte" },
  { id: 7, codigo: "2.3", descripcion: "Comunicaciones y Fletes" },
  { id: 8, codigo: "3.1", descripcion: "Edificios del campamento" },
  { id: 9, codigo: "3.2", descripcion: "Caminos, puentes y cerramientos" },
  { id: 10, codigo: "3.3", descripcion: "Servicios Basicos" },
  { id: 11, codigo: "3.4", descripcion: "Talleres de la Obra" },
  { id: 12, codigo: "3.5", descripcion: "Arriendos" },
  { id: 13, codigo: "4.1", descripcion: "Entretenimiento" },
  { id: 14, codigo: "4.2", descripcion: "Costos medicos, legales y otros" },
  { id: 15, codigo: "4.3", descripcion: "Seguros, garantias e impuestos" },
  { id: 16, codigo: "4.4", descripcion: "Gastos Varios" },
  { id: 17, codigo: "5.1", descripcion: "Material de consumo" },
  { id: 18, codigo: "5.2", descripcion: "Reparacion y mantenimiento de equipos" },
  { id: 19, codigo: "5.3", descripcion: "Herramientas" },
  { id: 21, codigo: "6.1", descripcion: "Utilidad" },
  { id: 22, codigo: "6.2", descripcion: "Imprevistos" },
  { id: 23, codigo: "7.1", descripcion: "Personalizados" }
];

export const INDIRECTOS_CONCEPTOS = [
  { id: 1, codPadre: "1.1", nombre: "Bonificaciones Especiales", fijo: false, usuario: false },
  { id: 2, codPadre: "1.1", nombre: "Almuerzo", fijo: false, usuario: false },
  { id: 3, codPadre: "1.1", nombre: "Uniformes", fijo: false, usuario: false },
  { id: 4, codPadre: "1.1", nombre: "Subsidio Familiar", fijo: false, usuario: false },
  { id: 5, codPadre: "1.1", nombre: "Otros", fijo: false, usuario: false },
  { id: 6, codPadre: "1.2", nombre: "Gastos técnicos generales", fijo: true, usuario: false },
  { id: 7, codPadre: "1.2", nombre: "Jefe de obra", fijo: false, usuario: false },
  { id: 8, codPadre: "1.2", nombre: "Ingeniero residentes y ayudantes", fijo: false, usuario: false },
  { id: 9, codPadre: "1.2", nombre: "Ingenieros de campo y ayudantes", fijo: false, usuario: false },
  { id: 10, codPadre: "1.2", nombre: "Ingeniero de oficina y ayudantes", fijo: false, usuario: false },
  { id: 11, codPadre: "1.3", nombre: "Ensayo de materiales", fijo: false, usuario: false },
  { id: 12, codPadre: "1.3", nombre: "Equipos y útiles de ingeniería", fijo: false, usuario: false },
  { id: 13, codPadre: "1.3", nombre: "Equipo de topografía", fijo: false, usuario: false },
  { id: 14, codPadre: "1.3", nombre: "Ingenieros consultores y servicios", fijo: false, usuario: false },
  { id: 15, codPadre: "1.3", nombre: "Fotos", fijo: false, usuario: false },
  { id: 16, codPadre: "1.4", nombre: "Gastos Administrativos Generales", fijo: true, usuario: false },
  { id: 17, codPadre: "1.4", nombre: "Empleados de oficina (Rol mensual)", fijo: false, usuario: false },
  { id: 18, codPadre: "1.4", nombre: "Equipos y muebles de oficina", fijo: false, usuario: false },
  { id: 19, codPadre: "1.4", nombre: "Útiles de oficina", fijo: false, usuario: false },
  { id: 20, codPadre: "1.4", nombre: "Refresco, café y otros", fijo: false, usuario: false },
  { id: 21, codPadre: "1.4", nombre: "Ploteos de planos", fijo: false, usuario: false },
  { id: 22, codPadre: "2.1", nombre: "Guardianía", fijo: false, usuario: false },
  { id: 23, codPadre: "2.1", nombre: "Bodega", fijo: false, usuario: false },
  { id: 24, codPadre: "2.1", nombre: "Conserjes de oficina", fijo: false, usuario: false },
  { id: 25, codPadre: "2.1", nombre: "Limpieza y mantenimiento", fijo: false, usuario: false },
  { id: 26, codPadre: "2.1", nombre: "Botiquín", fijo: false, usuario: false },
  { id: 27, codPadre: "2.2", nombre: "Choferes", fijo: false, usuario: false },
  { id: 28, codPadre: "2.2", nombre: "Matrículas, multas, permisos, etc.", fijo: false, usuario: false },
  { id: 29, codPadre: "2.2", nombre: "Alquiler de transporte", fijo: false, usuario: false },
  { id: 30, codPadre: "2.2", nombre: "Combustible", fijo: false, usuario: false },
  { id: 31, codPadre: "2.2", nombre: "Peajes", fijo: false, usuario: false },
  { id: 32, codPadre: "2.2", nombre: "Aceite y otros", fijo: false, usuario: false },
  { id: 33, codPadre: "2.3", nombre: "Uso y mantenimiento de aparatos de comunicación", fijo: false, usuario: false },
  { id: 34, codPadre: "2.3", nombre: "Celulares y planes", fijo: false, usuario: false },
  { id: 35, codPadre: "2.3", nombre: "Movilización de equipos", fijo: false, usuario: false },
  { id: 36, codPadre: "2.3", nombre: "Flete por tierra", fijo: false, usuario: false },
  { id: 37, codPadre: "2.3", nombre: "Flete por avión", fijo: false, usuario: false },
  { id: 38, codPadre: "2.3", nombre: "Flete marítimo", fijo: false, usuario: false },
  { id: 39, codPadre: "2.3", nombre: "Servicio de courier", fijo: false, usuario: false },
  { id: 40, codPadre: "3.1", nombre: "Materiales y gastos de construcción", fijo: false, usuario: false },
  { id: 41, codPadre: "3.1", nombre: "Mano de obra", fijo: false, usuario: false },
  { id: 42, codPadre: "3.2", nombre: "Construcciones y mantenimiento", fijo: false, usuario: false },
  { id: 43, codPadre: "3.2", nombre: "Mantenimiento de vías de acceso", fijo: false, usuario: false },
  { id: 44, codPadre: "3.3", nombre: "Instalaciones eléctricas y de internet", fijo: false, usuario: false },
  { id: 45, codPadre: "3.3", nombre: "Instalaciones sanitarias", fijo: false, usuario: false },
  { id: 46, codPadre: "3.3", nombre: "Tasas y permisos", fijo: false, usuario: false },
  { id: 47, codPadre: "3.3", nombre: "Consumo eléctrico", fijo: false, usuario: false },
  { id: 49, codPadre: "3.3", nombre: "Materiales y accesorios sanitarios", fijo: false, usuario: false },
  { id: 50, codPadre: "3.3", nombre: "Consumo de agua", fijo: false, usuario: false },
  { id: 51, codPadre: "3.4", nombre: "Excavación, relleno, compactación y pavimento", fijo: false, usuario: false },
  { id: 52, codPadre: "3.4", nombre: "Instalación de talleres", fijo: false, usuario: false },
  { id: 53, codPadre: "3.5", nombre: "Gastos por renta de terrenos", fijo: false, usuario: false },
  { id: 54, codPadre: "3.5", nombre: "Arriendo de bodega", fijo: false, usuario: false },
  { id: 55, codPadre: "3.5", nombre: "Arriendo de oficinas", fijo: false, usuario: false },
  { id: 56, codPadre: "4.1", nombre: "Gastos de entretenimiento", fijo: false, usuario: false },
  { id: 57, codPadre: "4.2", nombre: "Servicios médicos externos", fijo: false, usuario: false },
  { id: 58, codPadre: "4.2", nombre: "Servicios legales y de auditoría", fijo: false, usuario: false },
  { id: 59, codPadre: "4.2", nombre: "Cargas notariales", fijo: false, usuario: false },
  { id: 60, codPadre: "4.3", nombre: "Garantía de fiel cumplimiento", fijo: true, usuario: false },
  { id: 61, codPadre: "4.3", nombre: "Garantía de anticipo", fijo: true, usuario: false },
  { id: 62, codPadre: "4.3", nombre: "Garantía de buen uso de materiales", fijo: true, usuario: false },
  { id: 63, codPadre: "4.3", nombre: "Seguros de equipos y vehículos", fijo: false, usuario: false },
  { id: 64, codPadre: "4.3", nombre: "Seguros de muebles y otros bienes", fijo: false, usuario: false },
  { id: 65, codPadre: "4.3", nombre: "Seguros todo riesgo", fijo: false, usuario: false },
  { id: 66, codPadre: "4.3", nombre: "Impuestos varios", fijo: true, usuario: false },
  { id: 67, codPadre: "4.4", nombre: "Cargos financieros y bancarios", fijo: true, usuario: false },
  { id: 68, codPadre: "4.4", nombre: "Contribuciones o bonificaciones especiales", fijo: false, usuario: false },
  { id: 69, codPadre: "4.4", nombre: "Viajes y viáticos", fijo: false, usuario: false },
  { id: 70, codPadre: "4.4", nombre: "Relaciones laborales", fijo: false, usuario: false },
  { id: 71, codPadre: "4.4", nombre: "Gastos de concursos o licitaciones", fijo: true, usuario: false },
  { id: 72, codPadre: "4.4", nombre: "Relaciones públicas", fijo: false, usuario: false },
  { id: 73, codPadre: "4.4", nombre: "Suscripciones o registros", fijo: false, usuario: false },
  { id: 74, codPadre: "4.4", nombre: "Limpieza final", fijo: false, usuario: false },
  { id: 75, codPadre: "4.4", nombre: "Seguridad Industrial", fijo: true, usuario: false },
  { id: 76, codPadre: "5.1", nombre: "Cabo, cables, cadenas, etc.", fijo: false, usuario: false },
  { id: 77, codPadre: "5.1", nombre: "Clavos, pernos, tornillos, etc.", fijo: false, usuario: false },
  { id: 78, codPadre: "5.1", nombre: "Otros materiales no asignados en costos directos", fijo: false, usuario: false },
  { id: 79, codPadre: "5.2", nombre: "Mecánicos y oficiales", fijo: false, usuario: false },
  { id: 80, codPadre: "5.2", nombre: "Repuestos", fijo: false, usuario: false },
  { id: 81, codPadre: "5.2", nombre: "Reparaciones externas", fijo: false, usuario: false },
  { id: 82, codPadre: "5.2", nombre: "Combustible, aceites y grasa", fijo: false, usuario: false },
  { id: 83, codPadre: "5.3", nombre: "Herramientas manuales", fijo: false, usuario: false },
  { id: 84, codPadre: "5.3", nombre: "Herramientas mayores", fijo: false, usuario: false },
  { id: 85, codPadre: "4.4", nombre: "Gastos Varios", fijo: false, usuario: false },
  { id: 86, codPadre: "6.1", nombre: "Utilidad", fijo: true, usuario: false },
  { id: 87, codPadre: "6.2", nombre: "Imprevistos", fijo: true, usuario: false },
  { id: 88, codPadre: "1.2", nombre: "Topógrafos, cadeneros y jornaleros", fijo: false, usuario: false },
  { id: 89, codPadre: "1.4", nombre: "Fotocopias de documentos", fijo: false, usuario: false },
  { id: 90, codPadre: "3.3", nombre: "Consumo de internet", fijo: false, usuario: false },
  { id: 93, codPadre: "7.1", nombre: "Preliminares", fijo: false, usuario: true },
  { id: 94, codPadre: "7.1", nombre: "Preliminares 2", fijo: false, usuario: true }
];

export const INDIRECTOS_CATEGORIA_MAP = INDIRECTOS_CATEGORIAS.reduce((acc, categoria) => {
  acc[categoria.codigo] = categoria;
  return acc;
}, {});

export const INDIRECTOS_CONCEPTOS_POR_CATEGORIA = INDIRECTOS_CONCEPTOS.reduce((acc, concepto) => {
  if (!acc[concepto.codPadre]) {
    acc[concepto.codPadre] = [];
  }
  acc[concepto.codPadre].push(concepto);
  return acc;
}, {});
