"""add_polinomica_models

Revision ID: 08de68570ae1
Revises: 95d4a6d42101
Create Date: 2026-03-14 11:04:34.154326
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '08de68570ae1'
down_revision = '95d4a6d42101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices_inec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indices_inec_codigo'), 'indices_inec', ['codigo'], unique=True)
    op.create_index(op.f('ix_indices_inec_id'), 'indices_inec', ['id'], unique=False)
    op.create_table('formula_polinomica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('coeficiente_fijo', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('costo_directo_total', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultima_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_polinomica_id'), 'formula_polinomica', ['id'], unique=False)
    op.create_index(op.f('ix_formula_polinomica_presupuesto_id'), 'formula_polinomica', ['presupuesto_id'], unique=True)
    op.create_table('cuadrilla_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('indice_inec_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_hh', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('coeficiente_incidencia', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_polinomica.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indice_inec_id'], ['indices_inec.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuadrilla_tipo_formula_id'), 'cuadrilla_tipo', ['formula_id'], unique=False)
    op.create_index(op.f('ix_cuadrilla_tipo_id'), 'cuadrilla_tipo', ['id'], unique=False)
    op.create_table('formula_polinomica_monomios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('simbolo', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('indice_inec_id', sa.Integer(), nullable=True),
    sa.Column('coeficiente', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_polinomica.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indice_inec_id'], ['indices_inec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_polinomica_monomios_formula_id'), 'formula_polinomica_monomios', ['formula_id'], unique=False)
    op.create_index(op.f('ix_formula_polinomica_monomios_id'), 'formula_polinomica_monomios', ['id'], unique=False)
    op.drop_constraint('apu_lineas_apu_hijo_id_fkey', 'apu_lineas', type_='foreignkey')
    op.create_foreign_key(None, 'apu_lineas', 'recursos', ['recurso_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'apu_lineas', 'apus', ['apu_hijo_id'], ['id'], ondelete='SET NULL')
    op.alter_column('apus', 'descripcion_normalizada',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_index(op.f('ix_apus_base_trabajo_id'), 'apus', ['base_trabajo_id'], unique=False)
    op.create_index(op.f('ix_apus_descripcion_normalizada'), 'apus', ['descripcion_normalizada'], unique=False)
    op.create_index(op.f('ix_apus_subcategoria_item_id'), 'apus', ['subcategoria_item_id'], unique=False)
    op.create_foreign_key(None, 'apus', 'categorias_recursos', ['categoria_id'], ['id'])
    op.create_unique_constraint('uq_base_trabajo_nombre_empresa', 'bases_trabajo', ['nombre', 'empresa_id'])
    op.alter_column('empresas', 'proy_secuencial',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('empresas', 'proy_secuencial_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('9'))
    op.alter_column('presupuesto_detalles', 'edt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('presupuesto_detalles', 'cantidad',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('presupuesto_detalles', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('presupuesto_detalles', 'precio_total',
               existing_type=sa.NUMERIC(precision=15, scale=4),
               type_=sa.DECIMAL(precision=15, scale=6),
               existing_nullable=True)
    op.create_index(op.f('ix_presupuesto_detalles_edt_id'), 'presupuesto_detalles', ['edt_id'], unique=False)
    op.drop_constraint('presupuesto_detalles_presupuesto_id_fkey', 'presupuesto_detalles', type_='foreignkey')
    op.drop_constraint('presupuesto_detalles_apu_id_fkey', 'presupuesto_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'presupuesto_detalles', 'apus', ['apu_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'presupuesto_detalles', 'presupuestos', ['presupuesto_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('presupuestos_proyecto_id_fkey', 'presupuestos', type_='foreignkey')
    op.drop_constraint('presupuestos_empresa_id_fkey', 'presupuestos', type_='foreignkey')
    op.create_foreign_key(None, 'presupuestos', 'proyectos', ['proyecto_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'presupuestos', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ux_proyecto_detalles_empresa_codigo_root', table_name='proyecto_detalles', postgresql_where='(empresa_id IS NOT NULL)')
    op.create_index(op.f('ix_proyectos_base_trabajo_id'), 'proyectos', ['base_trabajo_id'], unique=False)
    op.create_index(op.f('ix_proyectos_codigo_root'), 'proyectos', ['codigo_root'], unique=False)
    op.alter_column('subcategorias_items', 'revisado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcategorias_items', 'revisado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_proyectos_codigo_root'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_base_trabajo_id'), table_name='proyectos')
    op.create_index('ux_proyecto_detalles_empresa_codigo_root', 'proyecto_detalles', ['empresa_id', 'codigo_root'], unique=True, postgresql_where='(empresa_id IS NOT NULL)')
    op.drop_constraint(None, 'presupuestos', type_='foreignkey')
    op.drop_constraint(None, 'presupuestos', type_='foreignkey')
    op.create_foreign_key('presupuestos_empresa_id_fkey', 'presupuestos', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key('presupuestos_proyecto_id_fkey', 'presupuestos', 'proyectos', ['proyecto_id'], ['id'])
    op.drop_constraint(None, 'presupuesto_detalles', type_='foreignkey')
    op.drop_constraint(None, 'presupuesto_detalles', type_='foreignkey')
    op.create_foreign_key('presupuesto_detalles_apu_id_fkey', 'presupuesto_detalles', 'apus', ['apu_id'], ['id'])
    op.create_foreign_key('presupuesto_detalles_presupuesto_id_fkey', 'presupuesto_detalles', 'presupuestos', ['presupuesto_id'], ['id'])
    op.drop_index(op.f('ix_presupuesto_detalles_edt_id'), table_name='presupuesto_detalles')
    op.alter_column('presupuesto_detalles', 'precio_total',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('presupuesto_detalles', 'precio_unitario',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('presupuesto_detalles', 'cantidad',
               existing_type=sa.DECIMAL(precision=15, scale=6),
               type_=sa.NUMERIC(precision=15, scale=4),
               existing_nullable=True)
    op.alter_column('presupuesto_detalles', 'edt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('empresas', 'proy_secuencial_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('9'))
    op.alter_column('empresas', 'proy_secuencial',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint('uq_base_trabajo_nombre_empresa', 'bases_trabajo', type_='unique')
    op.drop_constraint(None, 'apus', type_='foreignkey')
    op.drop_index(op.f('ix_apus_subcategoria_item_id'), table_name='apus')
    op.drop_index(op.f('ix_apus_descripcion_normalizada'), table_name='apus')
    op.drop_index(op.f('ix_apus_base_trabajo_id'), table_name='apus')
    op.alter_column('apus', 'descripcion_normalizada',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_constraint(None, 'apu_lineas', type_='foreignkey')
    op.drop_constraint(None, 'apu_lineas', type_='foreignkey')
    op.create_foreign_key('apu_lineas_apu_hijo_id_fkey', 'apu_lineas', 'apus', ['apu_hijo_id'], ['id'])
    op.drop_index(op.f('ix_formula_polinomica_monomios_id'), table_name='formula_polinomica_monomios')
    op.drop_index(op.f('ix_formula_polinomica_monomios_formula_id'), table_name='formula_polinomica_monomios')
    op.drop_table('formula_polinomica_monomios')
    op.drop_index(op.f('ix_cuadrilla_tipo_id'), table_name='cuadrilla_tipo')
    op.drop_index(op.f('ix_cuadrilla_tipo_formula_id'), table_name='cuadrilla_tipo')
    op.drop_table('cuadrilla_tipo')
    op.drop_index(op.f('ix_formula_polinomica_presupuesto_id'), table_name='formula_polinomica')
    op.drop_index(op.f('ix_formula_polinomica_id'), table_name='formula_polinomica')
    op.drop_table('formula_polinomica')
    op.drop_index(op.f('ix_indices_inec_id'), table_name='indices_inec')
    op.drop_index(op.f('ix_indices_inec_codigo'), table_name='indices_inec')
    op.drop_table('indices_inec')
    # ### end Alembic commands ###
