"""Add tipo and config_desglose to formula_polinomica

Revision ID: 0dc3d6b98ee0
Revises: 08de68570ae1
Create Date: 2026-03-14 12:10:39.125729
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0dc3d6b98ee0'
down_revision = '08de68570ae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula_polinomica', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('formula_polinomica', sa.Column('config_desglose', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formula_polinomica', 'config_desglose')
    op.drop_column('formula_polinomica', 'tipo')
    # ### end Alembic commands ###
