"""add_assign_modulo_es_global

Revision ID: 2f014d9a72ab
Revises: 6e273af7f68e
Create Date: 2026-03-17 07:38:37.329991
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2f014d9a72ab'
down_revision = '6e273af7f68e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresas', 'logo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('empresas', 'session_timeout_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.add_column('proyectos_asignaciones', sa.Column('modulo', sa.String(length=50), nullable=True))
    op.add_column('proyectos_asignaciones', sa.Column('es_global', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_proyectos_asignaciones_edt_id'), 'proyectos_asignaciones', ['edt_id'], unique=False)
    op.create_index(op.f('ix_proyectos_asignaciones_es_global'), 'proyectos_asignaciones', ['es_global'], unique=False)
    op.create_index(op.f('ix_proyectos_asignaciones_modulo'), 'proyectos_asignaciones', ['modulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proyectos_asignaciones_modulo'), table_name='proyectos_asignaciones')
    op.drop_index(op.f('ix_proyectos_asignaciones_es_global'), table_name='proyectos_asignaciones')
    op.drop_index(op.f('ix_proyectos_asignaciones_edt_id'), table_name='proyectos_asignaciones')
    op.drop_column('proyectos_asignaciones', 'es_global')
    op.drop_column('proyectos_asignaciones', 'modulo')
    op.alter_column('empresas', 'session_timeout_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('empresas', 'logo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
