"""fix_ondelete_and_nullability_task_0138

Revision ID: 49865d19f342
Revises: f3c95febc7e7
Create Date: 2026-03-16 06:57:55.039345
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '49865d19f342'
down_revision = 'f3c95febc7e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('apus_categoria_id_fkey', 'apus', type_='foreignkey')
    op.drop_constraint('apus_empresa_id_fkey', 'apus', type_='foreignkey')
    op.drop_constraint('apus_base_trabajo_id_fkey', 'apus', type_='foreignkey')
    op.create_foreign_key(None, 'apus', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'apus', 'categorias_recursos', ['categoria_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'apus', 'bases_trabajo', ['base_trabajo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('proyectos_empresa_id_fkey', 'proyectos', type_='foreignkey')
    op.create_foreign_key(None, 'proyectos', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recursos_cod_cpc_id_fkey', 'recursos', type_='foreignkey')
    op.create_foreign_key(None, 'recursos', 'codcpc', ['cod_cpc_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('roles_empresa_id_fkey', 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stakeholders_empresa_id_fkey', 'stakeholders', type_='foreignkey')
    op.create_foreign_key(None, 'stakeholders', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subcategorias_items_empresa_id_fkey', 'subcategorias_items', type_='foreignkey')
    op.create_foreign_key(None, 'subcategorias_items', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unidades_empresa_id_fkey', 'unidades', type_='foreignkey')
    op.drop_constraint('unidades_base_trabajo_id_fkey', 'unidades', type_='foreignkey')
    op.create_foreign_key(None, 'unidades', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'unidades', 'bases_trabajo', ['base_trabajo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('usuarios_empresa_id_fkey', 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key('usuarios_empresa_id_fkey', 'usuarios', 'empresas', ['empresa_id'], ['id'])
    op.drop_constraint(None, 'unidades', type_='foreignkey')
    op.drop_constraint(None, 'unidades', type_='foreignkey')
    op.create_foreign_key('unidades_base_trabajo_id_fkey', 'unidades', 'bases_trabajo', ['base_trabajo_id'], ['id'])
    op.create_foreign_key('unidades_empresa_id_fkey', 'unidades', 'empresas', ['empresa_id'], ['id'])
    op.drop_constraint(None, 'subcategorias_items', type_='foreignkey')
    op.create_foreign_key('subcategorias_items_empresa_id_fkey', 'subcategorias_items', 'empresas', ['empresa_id'], ['id'])
    op.drop_constraint(None, 'stakeholders', type_='foreignkey')
    op.create_foreign_key('stakeholders_empresa_id_fkey', 'stakeholders', 'empresas', ['empresa_id'], ['id'])
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key('roles_empresa_id_fkey', 'roles', 'empresas', ['empresa_id'], ['id'])
    op.drop_constraint(None, 'recursos', type_='foreignkey')
    op.create_foreign_key('recursos_cod_cpc_id_fkey', 'recursos', 'codcpc', ['cod_cpc_id'], ['id'])
    op.drop_constraint(None, 'proyectos', type_='foreignkey')
    op.create_foreign_key('proyectos_empresa_id_fkey', 'proyectos', 'empresas', ['empresa_id'], ['id'])
    op.drop_constraint(None, 'apus', type_='foreignkey')
    op.drop_constraint(None, 'apus', type_='foreignkey')
    op.drop_constraint(None, 'apus', type_='foreignkey')
    op.create_foreign_key('apus_base_trabajo_id_fkey', 'apus', 'bases_trabajo', ['base_trabajo_id'], ['id'])
    op.create_foreign_key('apus_empresa_id_fkey', 'apus', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key('apus_categoria_id_fkey', 'apus', 'categorias_recursos', ['categoria_id'], ['id'])
    # ### end Alembic commands ###
