"""stabilization_phase_5_precision_ondelete

Revision ID: 5d9a77f6f4f1
Revises: a4f2f394270a
Create Date: 2026-03-14 18:43:16.609476
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5d9a77f6f4f1'
down_revision = 'a4f2f394270a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cuadrilla_tipo_recurso_id_fkey', 'cuadrilla_tipo', type_='foreignkey')
    op.create_foreign_key(None, 'cuadrilla_tipo', 'recursos', ['recurso_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('presupuesto_detalles_parent_id_fkey', 'presupuesto_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'presupuesto_detalles', 'presupuesto_detalles', ['parent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recursos', 'precio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('recursos', 'precio_original',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('recursos', 'precio_tanteo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=18, scale=4),
               existing_nullable=True)
    op.drop_constraint('recursos_base_trabajo_id_fkey', 'recursos', type_='foreignkey')
    op.drop_constraint('recursos_empresa_id_fkey', 'recursos', type_='foreignkey')
    op.drop_constraint('recursos_unidad_id_fkey', 'recursos', type_='foreignkey')
    op.create_foreign_key(None, 'recursos', 'bases_trabajo', ['base_trabajo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recursos', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recursos', 'unidades', ['unidad_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recursos', type_='foreignkey')
    op.drop_constraint(None, 'recursos', type_='foreignkey')
    op.drop_constraint(None, 'recursos', type_='foreignkey')
    op.create_foreign_key('recursos_unidad_id_fkey', 'recursos', 'unidades', ['unidad_id'], ['id'])
    op.create_foreign_key('recursos_empresa_id_fkey', 'recursos', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key('recursos_base_trabajo_id_fkey', 'recursos', 'bases_trabajo', ['base_trabajo_id'], ['id'])
    op.alter_column('recursos', 'precio_tanteo',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('recursos', 'precio_original',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('recursos', 'precio',
               existing_type=sa.DECIMAL(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'presupuesto_detalles', type_='foreignkey')
    op.create_foreign_key('presupuesto_detalles_parent_id_fkey', 'presupuesto_detalles', 'presupuesto_detalles', ['parent_id'], ['id'])
    op.drop_constraint(None, 'cuadrilla_tipo', type_='foreignkey')
    op.create_foreign_key('cuadrilla_tipo_recurso_id_fkey', 'cuadrilla_tipo', 'recursos', ['recurso_id'], ['id'])
    # ### end Alembic commands ###
