"""Add formula_polinomica_asignaciones table

Revision ID: a4f2f394270a
Revises: 0dc3d6b98ee0
Create Date: 2026-03-14 13:09:34.966007
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a4f2f394270a'
down_revision = '0dc3d6b98ee0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula_polinomica_asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('simbolo', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_polinomica.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formula_id', 'recurso_id', name='uq_formula_recurso_asignacion')
    )
    op.create_index(op.f('ix_formula_polinomica_asignaciones_formula_id'), 'formula_polinomica_asignaciones', ['formula_id'], unique=False)
    op.create_index(op.f('ix_formula_polinomica_asignaciones_id'), 'formula_polinomica_asignaciones', ['id'], unique=False)
    op.create_index(op.f('ix_formula_polinomica_asignaciones_recurso_id'), 'formula_polinomica_asignaciones', ['recurso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formula_polinomica_asignaciones_recurso_id'), table_name='formula_polinomica_asignaciones')
    op.drop_index(op.f('ix_formula_polinomica_asignaciones_id'), table_name='formula_polinomica_asignaciones')
    op.drop_index(op.f('ix_formula_polinomica_asignaciones_formula_id'), table_name='formula_polinomica_asignaciones')
    op.drop_table('formula_polinomica_asignaciones')
    # ### end Alembic commands ###
