"""Add BIM commissioning asset and system registry."""
from alembic import op
import sqlalchemy as sa
revision="de2046a1b2c3"; down_revision="de2045a1b2c3"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("bim_commissioning_systems",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("empresa_id",sa.Integer(),sa.ForeignKey("empresas.id",ondelete="CASCADE"),nullable=False),sa.Column("proyecto_id",sa.Integer(),sa.ForeignKey("proyectos.id",ondelete="CASCADE"),nullable=False),sa.Column("system_code",sa.String(100),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("discipline",sa.String(100)),sa.Column("description",sa.Text()),sa.Column("status",sa.String(30),nullable=False,server_default="registered"),sa.Column("created_by",sa.Integer(),sa.ForeignKey("usuarios.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("status IN ('registered','commissioning','accepted','retired')",name="ck_bim_commissioning_system_status"),sa.UniqueConstraint("empresa_id","proyecto_id","system_code",name="uq_bim_commissioning_system_code"))
    op.create_table("bim_commissioning_assets",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("empresa_id",sa.Integer(),sa.ForeignKey("empresas.id",ondelete="CASCADE"),nullable=False),sa.Column("proyecto_id",sa.Integer(),sa.ForeignKey("proyectos.id",ondelete="CASCADE"),nullable=False),sa.Column("system_id",sa.Integer(),sa.ForeignKey("bim_commissioning_systems.id",ondelete="RESTRICT"),nullable=False),sa.Column("bim_model_version_id",sa.Integer(),sa.ForeignKey("bim_model_versions.id",ondelete="RESTRICT"),nullable=False),sa.Column("bim_element_id",sa.Integer(),sa.ForeignKey("bim_elements.id",ondelete="RESTRICT"),nullable=False),sa.Column("asset_tag",sa.String(100),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("asset_type",sa.String(100),nullable=False),sa.Column("global_id",sa.String(255),nullable=False),sa.Column("source_system_name",sa.String(255)),sa.Column("manufacturer",sa.String(255)),sa.Column("model_reference",sa.String(255)),sa.Column("serial_number",sa.String(255)),sa.Column("status",sa.String(30),nullable=False,server_default="registered"),sa.Column("created_by",sa.Integer(),sa.ForeignKey("usuarios.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("status IN ('registered','testing','accepted','rejected','retired')",name="ck_bim_commissioning_asset_status"),sa.UniqueConstraint("empresa_id","proyecto_id","asset_tag",name="uq_bim_commissioning_asset_tag"))
    for table,columns in (("bim_commissioning_systems",("empresa_id","proyecto_id","status")),("bim_commissioning_assets",("empresa_id","proyecto_id","system_id","bim_model_version_id","bim_element_id","status"))):
        for column in columns: op.create_index(f"ix_{table}_{column}",table,[column])
def downgrade(): op.drop_table("bim_commissioning_assets"); op.drop_table("bim_commissioning_systems")
