"""Add governed BIM cost forecasts."""
from alembic import op
import sqlalchemy as sa
revision="de2044a1b2c3"; down_revision="de2043a1b2c3"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("bim_cost_forecasts", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("empresa_id",sa.Integer(),sa.ForeignKey("empresas.id",ondelete="CASCADE"),nullable=False), sa.Column("proyecto_id",sa.Integer(),sa.ForeignKey("proyectos.id",ondelete="CASCADE"),nullable=False), sa.Column("estimate_id",sa.Integer(),sa.ForeignKey("bim_cost_estimates.id",ondelete="RESTRICT"),nullable=False), sa.Column("revision",sa.String(100),nullable=False), sa.Column("currency",sa.String(3),nullable=False), sa.Column("baseline_budget",sa.Numeric(18,2),nullable=False), sa.Column("committed_cost",sa.Numeric(18,2),nullable=False), sa.Column("actual_cost",sa.Numeric(18,2),nullable=False), sa.Column("estimate_to_complete",sa.Numeric(18,2),nullable=False), sa.Column("forecast_at_completion",sa.Numeric(18,2),nullable=False), sa.Column("variance_at_completion",sa.Numeric(18,2),nullable=False), sa.Column("rationale",sa.Text(),nullable=False), sa.Column("status",sa.String(30),nullable=False,server_default="draft"), sa.Column("decision_reason",sa.Text()), sa.Column("lock_version",sa.Integer(),nullable=False,server_default="1"), sa.Column("created_by",sa.Integer(),sa.ForeignKey("usuarios.id",ondelete="SET NULL")), sa.Column("decided_by",sa.Integer(),sa.ForeignKey("usuarios.id",ondelete="SET NULL")), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()), sa.Column("decided_at",sa.DateTime(timezone=True)), sa.CheckConstraint("estimate_to_complete >= 0 AND forecast_at_completion >= 0",name="ck_bim_cost_forecast_nonnegative"), sa.CheckConstraint("status IN ('draft','approved','rejected','superseded')",name="ck_bim_cost_forecast_status"), sa.UniqueConstraint("empresa_id","proyecto_id","currency","revision",name="uq_bim_cost_forecast_revision"))
    for column in ("empresa_id","proyecto_id","estimate_id","status"): op.create_index(f"ix_bim_cost_forecasts_{column}","bim_cost_forecasts",[column])
    op.create_index("uq_bim_cost_forecast_approved","bim_cost_forecasts",["empresa_id","proyecto_id","currency"],unique=True,postgresql_where=sa.text("status = 'approved'"))
def downgrade(): op.drop_table("bim_cost_forecasts")
