"""Add cronograma_trabajo table

Revision ID: f3c95febc7e7
Revises: 5d9a77f6f4f1
Create Date: 2026-03-15 13:57:24.973416
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f3c95febc7e7'
down_revision = '5d9a77f6f4f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cronogramas_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('presupuesto_id', sa.Integer(), nullable=False),
    sa.Column('schedule_data', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presupuesto_id'], ['presupuestos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presupuesto_id', name='uq_cronogramas_trabajo_presupuesto_id')
    )
    op.create_index(op.f('ix_cronogramas_trabajo_empresa_id'), 'cronogramas_trabajo', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cronogramas_trabajo_id'), 'cronogramas_trabajo', ['id'], unique=False)
    op.create_index(op.f('ix_cronogramas_trabajo_presupuesto_id'), 'cronogramas_trabajo', ['presupuesto_id'], unique=False)
    op.create_index(op.f('ix_cronogramas_trabajo_proyecto_id'), 'cronogramas_trabajo', ['proyecto_id'], unique=False)
    op.alter_column('cronogramas_valorados', 'global_distribution',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('cronogramas_valorados', 'line_distribution_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('empresas', 'plantillas_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('formula_polinomica', 'config_desglose',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('proyectos', 'plantillas_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proyectos', 'plantillas_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('formula_polinomica', 'config_desglose',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('empresas', 'plantillas_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cronogramas_valorados', 'line_distribution_overrides',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('cronogramas_valorados', 'global_distribution',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_cronogramas_trabajo_proyecto_id'), table_name='cronogramas_trabajo')
    op.drop_index(op.f('ix_cronogramas_trabajo_presupuesto_id'), table_name='cronogramas_trabajo')
    op.drop_index(op.f('ix_cronogramas_trabajo_id'), table_name='cronogramas_trabajo')
    op.drop_index(op.f('ix_cronogramas_trabajo_empresa_id'), table_name='cronogramas_trabajo')
    op.drop_table('cronogramas_trabajo')
    # ### end Alembic commands ###
